### ISSUE TITLE
Footer near top while loading

### ISSUE THREAD

**Issue by benhalpern** [tylerbmcsilva/impeachment-2019#4]
The site's fast and loading is pleasant, but the footer shows before the content is loaded. And then it's pushed to the bottom.

I think most likely there should be a minimum height for the content of `100vh` to keep the footer below the fold.

**Comment by tymc7** [comment]
Thanks @benhalpern, I agree that it should be hidden prior to the content loading. Just pushed an update and it should be fixed! 👍 

https://www.impeachment.dev
